repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: trailing-whitespace
    exclude: business/tests/data/mail/kl_to_1c.txt
  - id: end-of-file-fixer
    exclude: business/tests/data/mail/kl_to_1c.txt
  - id: double-quote-string-fixer

- repo: https://github.com/myint/autoflake
  rev: v1.6.1
  hooks:
  - id: autoflake
    args: ['--in-place', '--remove-all-unused-imports']
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.10.1'
  hooks:
  - id: isort
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.3.0
  hooks:
  - id: add-trailing-comma
    exclude: ^(data|\w+/migrations)/

- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: ^(data|\w+/migrations)/
    args: ['--max-line-length=160']
