version: "3.9"  # version of docker-compose syntax

# specify services. It is usually one or more service
services:
  app:  # name of service
    build:  # building section
      context: .  # it points that we want to build a Dockerfile in current directory
      args:  # by default this argument is set to false in Dockerfile. We overwrite it in docker-compose
        - DEV=true
    ports:  # it maps port local machine to port inside docker container.
      - "8000:8000"
    # it is way of mapping directories from our system to container directory.
    # If we make update locally it will be reflected in current container
    volumes:
      - ./app:/app
    # command that is used to run service. It can be overwrited command with run command on docker-compose
    # but by default it runs this command
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data: